controller_manager:
  ros__parameters:
    update_rate: 100
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
     
    
    joints_position_controllers:
      type: effort_controllers/JointGroupEffortController
      
  
  # Position Controllers ---------------------------------------
joint_state_broadcaster:
   ros__parameters:
    joints:
      - link_head_1_joint
      - link_1_2_joint
      - link_2_3_joint
      - link_3_4_joint
      - link_4_5_joint
      - link_5_6_joint
      - link_6_7_joint
      - link_7_8_joint
      - link_8_9_joint  
    



joints_position_controllers:
   ros__parameters:
    joints:
      - link_head_1_joint
      - link_1_2_joint
      - link_2_3_joint
      - link_3_4_joint
      - link_4_5_joint
      - link_5_6_joint
      - link_6_7_joint
      - link_7_8_joint
      - link_8_9_joint  

    interface_name: effort
    
    
    command_interfaces:
      - effort    

  
  
  
  
  
  
          
